dev:
  author.url: http://localhost:5000
  author.ip: http://127.0.0.1:5000
  author.login: admin
  author.password: admin
  login.token.name: login-token
  
  publish.url: http://localhost:443
  publish.ip: http://127.0.0.1:443  
  publish.login: admin
  publish.password: admin
